fix: methods named `new`
TypeScript treats `new(...P): R;` in an object type as a constructor signature.
The caller is then expected to call the method like a constructor,
e.g. `new mod.struct(...args)`, which is incorrect.

With that syntax, the method called correctly, `mod.struct.new(...args)`, raises an error:
> Property 'new' does not exist on type 'T'.

The fix is to make `new` a regular property with a function signature.