fix(types): use special 'new' decl for struct etc due to it reserved in TS + immutable array arguments (#127)
* fix: methods named `new`

TypeScript treats `new(...P): R;` in an object type as a constructor signature.
The caller is then expected to call the method like a constructor,
e.g. `new mod.struct(...args)`, which is incorrect.

With that syntax, the method called correctly, `mod.struct.new(...args)`, raises an error:
> Property 'new' does not exist on type 'T'.

The fix is to make `new` a regular property with a function signature.

* fix: `struct.new@operands` type

* refactor: allow readonly array arguments

Widens parameter types to include readonly arrays.

Sometimes a caller may have a readonly array they want to pass
into a function. If the function expects a writeable array,
the assignment is not allowed:
> The type 'readonly T[]' is 'readonly' and cannot be assigned to the mutable type 'T[]'.
This forces the caller to use spread syntax, concating/slicing, type casting,
or other ‘hacky’ techniques to resolve the error.

By making the parameter type `readonly T[]`,
we’re promising the caller that the method will never mutate the array.

* lint: whitespace